services:
  mqtt:
    image: "eclipse-mosquitto:latest"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883
  metrics:
    build: "metrics-server"
    environment:
      - MQTT_TOPIC=rtl_433/+/events
    depends_on:
      mqtt:
        condition: service_started
        restart: true
    ports:
      - 8080:8080
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
volumes:
  prometheus-data:
