---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: weather-metrics
data:
  # file-like keys
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: weather-metrics
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto:latest
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: mqtt-config
          items:
          - key: "mosquitto.conf"
            path: "mosquitto.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: weather-metrics
  labels:
    app: mqtt
spec:
    ports:
    - name: mqtt
      port: 1883
    type: ClusterIP
    selector:
      app: mqtt
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-external
  namespace: weather-metrics
  labels:
    app: mqtt
spec:
    ports:
    - name: mqtt
      port: 1883
    type: LoadBalancer
    selector:
      app: mqtt
