apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: weather-metrics
data:
  # file-like keys
  prometheus.yml: |
    scrape_configs:
    - job_name: "prometheus"

      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

      static_configs:
        - targets: ["localhost:9090"]
        # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
          labels:
            app: "prometheus"
    - job_name: weather-metrics
      static_configs:
        - targets:
          - weather-metrics:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: weather-metrics
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: "prom/prometheus"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: prometheus-config
          items:
          - key: "prometheus.yml"
            path: "prometheus.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: weather-metrics
  labels:
    app: prometheus
spec:
    ports:
    - name: prometheus
      port: 9090
    type: LoadBalancer
    selector:
      app: prometheus