apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-config
  namespace: weather-metrics
data:
  MQTT_TOPIC: rtl_433/+/events
---
apiVersion: v1
kind: Pod
metadata:
  name: weather-metrics
  namespace: weather-metrics
  labels:
    app: weather-metrics
spec:
  containers:
  - name: weather-metrics
    image: registry.mckeownlab.diy/prometheus-proxy:v0.2
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: metrics-config
---
apiVersion: v1
kind: Service
metadata:
  name: weather-metrics
  namespace: weather-metrics
  labels:
    app: weather-metrics
spec:
    ports:
    - name: weather-metrics
      port: 8080
    type: ClusterIP
    selector:
      app: weather-metrics

